apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: brunomarch/gitopsfc
  newTag: 954d5750be71a0d70a79c4da72003b3e93270316
