apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: brunomarch/gitopsfc
  newTag: e41c52463c047403c972baf55672c222755d299f
